Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-053b0d53c279acc90
      Tags:
        - Key:   "Name"
          Value: !Join
            - " "
            - - "My instance in"
              - !Ref AWS::Region

      SecurityGroups:
        - !Ref TestSG
  TestSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http && ssh from my host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 213.91.249.122/32

